# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [thongngo, thongngo-vbtc, vbtc, bitcoinvn]
patreon: # Replace with a single Patreon username thongngo 
open_collective: # Replace with a single Open Collective username thongngo 
ko_fi: # Replace with a single Ko-fi username thongngo 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., thongngo-vbtc
community_bridge: # Replace with a single Community Bridge project-name e.g., thongngo-vbtc
liberapay: # Replace with a single Liberapay username thongngo
issuehunt: # Replace with a single IssueHunt username thongngo
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['vbtc.exchange', 'github.vbtc.io', 'github.com/Quang7hong81/THONG-NGO-VBTC]
 
# Author: THONG NGO
